version: "3.8"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: app_frontend
    container_name: frontend_app
    ports:
      - "80:80"
    environment:
      NODE_ENV: production
    depends_on:
      - server
    develop:
      watch:
        - action: sync
          path: ./app
          target: /src/web
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server_backend
    container_name: rust_server
    ports:
      - "8080:8080"
    environment:
      RUST_LOG: info
